config/routes.rb
Modalware::Application.routes.draw do
  resources :comments

  resources :views_emails

  resources :views

  resources :pieces

  resources :jobs

  resources :data_groups

  resources :groups

  resources :data_tags

  resources :containers

  resources :tags

  resources :users, :except => [:destroy, :index]

  root :to => "welcome#index"
  match 'welcome/:action' => 'welcome#action'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/container.rb
class Container < ActiveRecord::Base
end

app/models/data_group.rb
class DataGroup < ActiveRecord::Base
end

app/models/data_tag.rb
class DataTag < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/piece.rb
class Piece < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email, :message => "This email has already been registered."
end

app/models/view.rb
class View < ActiveRecord::Base
end

app/models/views_email.rb
class ViewsEmail < ActiveRecord::Base
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  # GET /containers
  # GET /containers.xml
  def index
    @containers = Container.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @containers }
    end
  end

  # GET /containers/1
  # GET /containers/1.xml
  def show
    @container = Container.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @container }
    end
  end

  # GET /containers/new
  # GET /containers/new.xml
  def new
    @container = Container.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @container }
    end
  end

  # GET /containers/1/edit
  def edit
    @container = Container.find(params[:id])
  end

  # POST /containers
  # POST /containers.xml
  def create
    @container = Container.new(params[:container])

    respond_to do |format|
      if @container.save
        format.html { redirect_to(@container, :notice => 'Container was successfully created.') }
        format.xml  { render :xml => @container, :status => :created, :location => @container }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @container.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /containers/1
  # PUT /containers/1.xml
  def update
    @container = Container.find(params[:id])

    respond_to do |format|
      if @container.update_attributes(params[:container])
        format.html { redirect_to(@container, :notice => 'Container was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @container.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.xml
  def destroy
    @container = Container.find(params[:id])
    @container.destroy

    respond_to do |format|
      format.html { redirect_to(containers_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/oauth_callback.rb
class OauthCallback < ApplicationController
  def index
    verifier = params[:oauth_verifier]
    token = params[:oauth_token]
    if token == session[:oauth_token]
      u = User.find session[:uid]
      l = Linker.new
      li_secret, li_token = l.auth_user(verifier)
      session[:li_secret] = li_secret
      session[:li_token]  = li_token
      u.linkedin_secret = li_secret
      u.linkedin_token = li_token
      u.linkedin_id = l.client.profile(:fields => ['id']).id
      u.save
    else
      #This is very, very bad
    end
    redirect_to :controller => :jobs, :action => 'initiate_synch_with_linkedin'
  end
  
  def start_li_call
    l = Linker.new
    render :url => l.client.request_token.authorize_url
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/data_tags_helper.rb
module DataTagsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/containers/_form.html.erb
<%= form_for(@container) do |f| %>
  <% if @container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
      <% @container.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :view_id %><br />
    <%= f.text_field :view_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.text_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :position_x %><br />
    <%= f.text_field :position_x %>
  </div>
  <div class="field">
    <%= f.label :position_y %><br />
    <%= f.text_field :position_y %>
  </div>
  <div class="field">
    <%= f.label :size_x %><br />
    <%= f.text_field :size_x %>
  </div>
  <div class="field">
    <%= f.label :size_y %><br />
    <%= f.text_field :size_y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<h1>Editing container</h1>

<%= render 'form' %>

<%= link_to 'Show', @container %> |
<%= link_to 'Back', containers_path %>

app/views/containers/index.html.erb
<h1>Listing containers</h1>

<table>
  <tr>
    <th>View</th>
    <th>Group</th>
    <th>Position x</th>
    <th>Position y</th>
    <th>Size x</th>
    <th>Size y</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @containers.each do |container| %>
  <tr>
    <td><%= container.view_id %></td>
    <td><%= container.group_id %></td>
    <td><%= container.position_x %></td>
    <td><%= container.position_y %></td>
    <td><%= container.size_x %></td>
    <td><%= container.size_y %></td>
    <td><%= link_to 'Show', container %></td>
    <td><%= link_to 'Edit', edit_container_path(container) %></td>
    <td><%= link_to 'Destroy', container, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Container', new_container_path %>

app/views/containers/new.html.erb
<h1>New container</h1>

<%= render 'form' %>

<%= link_to 'Back', containers_path %>

app/views/containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>View:</b>
  <%= @container.view_id %>
</p>

<p>
  <b>Group:</b>
  <%= @container.group_id %>
</p>

<p>
  <b>Position x:</b>
  <%= @container.position_x %>
</p>

<p>
  <b>Position y:</b>
  <%= @container.position_y %>
</p>

<p>
  <b>Size x:</b>
  <%= @container.size_x %>
</p>

<p>
  <b>Size y:</b>
  <%= @container.size_y %>
</p>


<%= link_to 'Edit', edit_container_path(@container) %> |
<%= link_to 'Back', containers_path %>