config/routes.rb
Modalware::Application.routes.draw do
  resources :comments

  resources :views_emails

  resources :views

  resources :pieces

  resources :jobs

  resources :data_groups

  resources :groups

  resources :data_tags

  resources :containers

  resources :tags

  resources :users, :except => [:destroy, :index]

  root :to => "welcome#index"
  match 'welcome/:action' => 'welcome#action'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/container.rb
class Container < ActiveRecord::Base
end

app/models/data_group.rb
class DataGroup < ActiveRecord::Base
end

app/models/data_tag.rb
class DataTag < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/piece.rb
class Piece < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email, :message => "This email has already been registered."
end

app/models/view.rb
class View < ActiveRecord::Base
end

app/models/views_email.rb
class ViewsEmail < ActiveRecord::Base
end

app/controllers/views_emails_controller.rb
class ViewsEmailsController < ApplicationController
  # GET /views_emails
  # GET /views_emails.xml
  def index
    @views_emails = ViewsEmail.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @views_emails }
    end
  end

  # GET /views_emails/1
  # GET /views_emails/1.xml
  def show
    @views_email = ViewsEmail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @views_email }
    end
  end

  # GET /views_emails/new
  # GET /views_emails/new.xml
  def new
    @views_email = ViewsEmail.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @views_email }
    end
  end

  # GET /views_emails/1/edit
  def edit
    @views_email = ViewsEmail.find(params[:id])
  end

  # POST /views_emails
  # POST /views_emails.xml
  def create
    @views_email = ViewsEmail.new(params[:views_email])

    respond_to do |format|
      if @views_email.save
        format.html { redirect_to(@views_email, :notice => 'Views email was successfully created.') }
        format.xml  { render :xml => @views_email, :status => :created, :location => @views_email }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @views_email.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /views_emails/1
  # PUT /views_emails/1.xml
  def update
    @views_email = ViewsEmail.find(params[:id])

    respond_to do |format|
      if @views_email.update_attributes(params[:views_email])
        format.html { redirect_to(@views_email, :notice => 'Views email was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @views_email.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /views_emails/1
  # DELETE /views_emails/1.xml
  def destroy
    @views_email = ViewsEmail.find(params[:id])
    @views_email.destroy

    respond_to do |format|
      format.html { redirect_to(views_emails_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/data_tags_helper.rb
module DataTagsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_emails_helper.rb
module ViewsEmailsHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/views_emails/_form.html.erb
<%= form_for(@views_email) do |f| %>
  <% if @views_email.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@views_email.errors.count, "error") %> prohibited this views_email from being saved:</h2>

      <ul>
      <% @views_email.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/views_emails/edit.html.erb
<h1>Editing views_email</h1>

<%= render 'form' %>

<%= link_to 'Show', @views_email %> |
<%= link_to 'Back', views_emails_path %>

app/views/views_emails/index.html.erb
<h1>Listing views_emails</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @views_emails.each do |views_email| %>
  <tr>
    <td><%= views_email.email %></td>
    <td><%= link_to 'Show', views_email %></td>
    <td><%= link_to 'Edit', edit_views_email_path(views_email) %></td>
    <td><%= link_to 'Destroy', views_email, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Views email', new_views_email_path %>

app/views/views_emails/new.html.erb
<h1>New views_email</h1>

<%= render 'form' %>

<%= link_to 'Back', views_emails_path %>

app/views/views_emails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @views_email.email %>
</p>


<%= link_to 'Edit', edit_views_email_path(@views_email) %> |
<%= link_to 'Back', views_emails_path %>